import 'package:flutter/services.dart' show rootBundle;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'attendance_stats.dart';
import 'report_service.dart';

/// Builds and shares/prints a colourful, Clockify-style PDF of a report.
class PdfReportService {
  static const _brand = PdfColor.fromInt(0xFF2E6BE6);

  PdfColor _colorOf(ReportNode n) =>
      n.color != null ? PdfColor.fromInt(n.color!) : PdfColors.blueGrey400;

  /// Loads the bundled Noto fonts (Latin + Bengali) for full offline Unicode.
  /// Falls back to the built-in font if the assets can't be read.
  Future<pw.ThemeData?> _loadTheme() async {
    try {
      final regular =
          pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSans-Regular.ttf'));
      final bold =
          pw.Font.ttf(await rootBundle.load('assets/fonts/NotoSans-Bold.ttf'));
      final bengali = pw.Font.ttf(
          await rootBundle.load('assets/fonts/NotoSansBengali-Regular.ttf'));
      return pw.ThemeData.withFont(
        base: regular,
        bold: bold,
        fontFallback: [bengali],
      );
    } catch (_) {
      return null;
    }
  }

  Future<pw.Document> build({
    required String title,
    required DateRange range,
    required List<ReportNode> nodes,
    required List<TimeBucket> daily,
    required Duration total,
  }) async {
    final theme = await _loadTheme();
    final doc = pw.Document(theme: theme);
    final dateFmt = DateFormat('dd MMM yyyy');
    final rangeText =
        '${dateFmt.format(range.start)} - ${dateFmt.format(range.end.subtract(const Duration(days: 1)))}';
    final totalMs = total.inMilliseconds == 0 ? 1 : total.inMilliseconds;
    final visible = nodes.where((n) => n.total.inSeconds > 0).toList();

    String pct(Duration d) =>
        '${(d.inMilliseconds / totalMs * 100).round()}%';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        build: (context) => [
          _header(title, rangeText, total),
          pw.SizedBox(height: 18),
          if (daily.isNotEmpty) ...[
            _sectionTitle('Daily activity'),
            pw.SizedBox(height: 8),
            _barChart(daily),
            pw.SizedBox(height: 20),
          ],
          if (visible.isNotEmpty) ...[
            _sectionTitle('Projects'),
            pw.SizedBox(height: 10),
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                _pie(visible),
                pw.SizedBox(width: 20),
                pw.Expanded(child: _legend(visible, pct)),
              ],
            ),
            pw.SizedBox(height: 22),
            _sectionTitle('Breakdown'),
            pw.SizedBox(height: 8),
            ...visible.map((p) => _projectBlock(p, totalMs, pct)),
          ],
          pw.SizedBox(height: 8),
          pw.Divider(),
          pw.Container(
            alignment: pw.Alignment.centerRight,
            child: pw.Text('Generated by AttendEase',
                style:
                    const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
          ),
        ],
      ),
    );
    return doc;
  }

  pw.Widget _header(String title, String rangeText, Duration total) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(18),
      decoration: const pw.BoxDecoration(
        color: _brand,
        borderRadius: pw.BorderRadius.all(pw.Radius.circular(12)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(title,
                  style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 22,
                      fontWeight: pw.FontWeight.bold)),
              pw.Text(rangeText,
                  style:
                      const pw.TextStyle(color: PdfColors.white, fontSize: 11)),
            ],
          ),
          pw.SizedBox(height: 12),
          pw.Text(formatHm(total),
              style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 32,
                  fontWeight: pw.FontWeight.bold)),
          pw.Text('Total tracked',
              style: const pw.TextStyle(color: PdfColors.white, fontSize: 10)),
        ],
      ),
    );
  }

  pw.Widget _sectionTitle(String text) => pw.Text(text,
      style: pw.TextStyle(
          fontSize: 13,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.grey800));

  pw.Widget _barChart(List<TimeBucket> buckets) {
    final maxMs = buckets
        .map((b) => b.total.inMilliseconds)
        .fold<int>(1, (a, b) => b > a ? b : a);
    const chartH = 90.0;
    return pw.Container(
      height: chartH + 16,
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.end,
        children: buckets.map((b) {
          final h = maxMs == 0 ? 0.0 : (b.total.inMilliseconds / maxMs) * chartH;
          return pw.Expanded(
            child: pw.Column(
              mainAxisSize: pw.MainAxisSize.min,
              mainAxisAlignment: pw.MainAxisAlignment.end,
              children: [
                pw.Container(
                  width: 11,
                  height: h < 1 ? 1 : h,
                  decoration: const pw.BoxDecoration(
                    color: _brand,
                    borderRadius: pw.BorderRadius.vertical(
                        top: pw.Radius.circular(2)),
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(b.label,
                    style:
                        const pw.TextStyle(fontSize: 7, color: PdfColors.grey600)),
              ],
            ),
          );
        }).toList(),
      ),
    );
  }

  pw.Widget _pie(List<ReportNode> nodes) {
    return pw.SizedBox(
      width: 130,
      height: 130,
      child: pw.Chart(
        grid: pw.PieGrid(),
        datasets: nodes
            .map((n) => pw.PieDataSet(
                  value: n.total.inMilliseconds.toDouble(),
                  color: _colorOf(n),
                  legend: '',
                ))
            .toList(),
      ),
    );
  }

  pw.Widget _legend(List<ReportNode> nodes, String Function(Duration) pct) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: nodes.map((n) {
        return pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 4),
          child: pw.Row(
            children: [
              pw.Container(
                width: 11,
                height: 11,
                decoration: pw.BoxDecoration(
                    color: _colorOf(n), shape: pw.BoxShape.circle),
              ),
              pw.SizedBox(width: 8),
              pw.Expanded(
                child: pw.Text(n.label, style: const pw.TextStyle(fontSize: 10)),
              ),
              pw.Text(pct(n.total),
                  style: const pw.TextStyle(
                      fontSize: 9, color: PdfColors.grey600)),
              pw.SizedBox(width: 10),
              pw.Text(formatHm(n.total),
                  style: pw.TextStyle(
                      fontSize: 10, fontWeight: pw.FontWeight.bold)),
            ],
          ),
        );
      }).toList(),
    );
  }

  pw.Widget _projectBlock(
      ReportNode project, int totalMs, String Function(Duration) pct) {
    final color = _colorOf(project);
    final fraction = project.total.inMilliseconds / totalMs;
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 10),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            children: [
              pw.Container(
                width: 12,
                height: 12,
                decoration:
                    pw.BoxDecoration(color: color, shape: pw.BoxShape.circle),
              ),
              pw.SizedBox(width: 8),
              pw.Expanded(
                child: pw.Text(project.label,
                    style: pw.TextStyle(
                        fontSize: 13, fontWeight: pw.FontWeight.bold)),
              ),
              pw.Text(pct(project.total),
                  style: const pw.TextStyle(
                      fontSize: 11, color: PdfColors.grey700)),
              pw.SizedBox(width: 12),
              pw.Text(formatHm(project.total),
                  style: pw.TextStyle(
                      fontSize: 13, fontWeight: pw.FontWeight.bold)),
            ],
          ),
          pw.SizedBox(height: 6),
          _bar(fraction, color),
          pw.SizedBox(height: 8),
          ...project.children.map((t) {
            final tFrac = project.total.inMilliseconds == 0
                ? 0.0
                : t.total.inMilliseconds / project.total.inMilliseconds;
            return pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 3),
              child: pw.Row(
                children: [
                  pw.Expanded(
                    flex: 5,
                    child: pw.Text(t.label,
                        style: const pw.TextStyle(fontSize: 10)),
                  ),
                  pw.Expanded(flex: 4, child: _bar(tFrac, color, height: 5)),
                  pw.SizedBox(width: 10),
                  pw.SizedBox(
                    width: 60,
                    child: pw.Text(formatHm(t.total),
                        textAlign: pw.TextAlign.right,
                        style: const pw.TextStyle(fontSize: 10)),
                  ),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }

  pw.Widget _bar(double fraction, PdfColor color, {double height = 8}) {
    final f = fraction.clamp(0.0, 1.0);
    final filled = (f * 1000).round();
    return pw.ClipRRect(
      horizontalRadius: height / 2,
      verticalRadius: height / 2,
      child: pw.Row(
        children: [
          if (filled > 0)
            pw.Expanded(
                flex: filled,
                child: pw.Container(height: height, color: color)),
          if (filled < 1000)
            pw.Expanded(
                flex: 1000 - filled,
                child: pw.Container(height: height, color: PdfColors.grey300)),
        ],
      ),
    );
  }

  /// Opens the system share sheet (Android) / save dialog (Windows).
  Future<void> share(pw.Document doc,
      {String filename = 'attendease_report.pdf'}) async {
    await Printing.sharePdf(bytes: await doc.save(), filename: filename);
  }

  /// Opens the print preview on both platforms.
  Future<void> printPreview(pw.Document doc) async {
    await Printing.layoutPdf(onLayout: (_) async => doc.save());
  }
}
