import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import 'attendance_stats.dart';
import 'report_service.dart';

/// Builds and shares/prints a colourful, Clockify-style PDF of a report.
class PdfReportService {
  static const _brand = PdfColor.fromInt(0xFF2E6BE6);

  PdfColor _colorOf(ReportNode n) =>
      n.color != null ? PdfColor.fromInt(n.color!) : PdfColors.blueGrey400;

  Future<pw.Document> build({
    required String title,
    required DateRange range,
    required List<ReportNode> nodes,
    required Duration total,
  }) async {
    final doc = pw.Document();
    final dateFmt = DateFormat('dd MMM yyyy');
    final rangeText =
        '${dateFmt.format(range.start)} – ${dateFmt.format(range.end.subtract(const Duration(days: 1)))}';
    final totalMs = total.inMilliseconds == 0 ? 1 : total.inMilliseconds;

    String pct(Duration d) =>
        '${(d.inMilliseconds / totalMs * 100).round()}%';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(28),
        build: (context) => [
          // ---- Header band ----
          pw.Container(
            width: double.infinity,
            padding: const pw.EdgeInsets.all(16),
            decoration: const pw.BoxDecoration(
              color: _brand,
              borderRadius: pw.BorderRadius.all(pw.Radius.circular(10)),
            ),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(title,
                        style: pw.TextStyle(
                            color: PdfColors.white,
                            fontSize: 20,
                            fontWeight: pw.FontWeight.bold)),
                    pw.Text(rangeText,
                        style: const pw.TextStyle(
                            color: PdfColors.white, fontSize: 11)),
                  ],
                ),
                pw.SizedBox(height: 10),
                pw.Text(formatHm(total),
                    style: pw.TextStyle(
                        color: PdfColors.white,
                        fontSize: 30,
                        fontWeight: pw.FontWeight.bold)),
                pw.Text('Total tracked',
                    style: const pw.TextStyle(
                        color: PdfColors.white, fontSize: 10)),
              ],
            ),
          ),
          pw.SizedBox(height: 16),

          // ---- Stacked total bar (per project) ----
          if (nodes.isNotEmpty) ...[
            pw.ClipRRect(
              horizontalRadius: 6,
              verticalRadius: 6,
              child: pw.Row(
                children: nodes
                    .map((n) => pw.Expanded(
                          flex: n.total.inSeconds <= 0 ? 1 : n.total.inSeconds,
                          child: pw.Container(height: 16, color: _colorOf(n)),
                        ))
                    .toList(),
              ),
            ),
            pw.SizedBox(height: 16),
          ],

          // ---- Per-project breakdown ----
          ...nodes.map((p) => _projectBlock(p, totalMs, pct)),

          pw.SizedBox(height: 8),
          pw.Divider(),
          pw.Container(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Generated by AttendEase',
              style:
                  const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
            ),
          ),
        ],
      ),
    );
    return doc;
  }

  pw.Widget _projectBlock(
      ReportNode project, int totalMs, String Function(Duration) pct) {
    final color = _colorOf(project);
    final fraction = project.total.inMilliseconds / totalMs;
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 14),
      padding: const pw.EdgeInsets.all(10),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
        border: pw.Border(left: pw.BorderSide(color: color, width: 4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Project header row
          pw.Row(
            children: [
              pw.Container(
                width: 12,
                height: 12,
                decoration: pw.BoxDecoration(
                    color: color, shape: pw.BoxShape.circle),
              ),
              pw.SizedBox(width: 8),
              pw.Expanded(
                child: pw.Text(project.label,
                    style: pw.TextStyle(
                        fontSize: 13, fontWeight: pw.FontWeight.bold)),
              ),
              pw.Text(pct(project.total),
                  style: const pw.TextStyle(
                      fontSize: 11, color: PdfColors.grey700)),
              pw.SizedBox(width: 12),
              pw.Text(formatHm(project.total),
                  style: pw.TextStyle(
                      fontSize: 13, fontWeight: pw.FontWeight.bold)),
            ],
          ),
          pw.SizedBox(height: 6),
          _bar(fraction, color),
          pw.SizedBox(height: 8),
          // Task rows
          ...project.children.map((t) {
            final tFrac = project.total.inMilliseconds == 0
                ? 0.0
                : t.total.inMilliseconds / project.total.inMilliseconds;
            return pw.Padding(
              padding: const pw.EdgeInsets.symmetric(vertical: 3),
              child: pw.Row(
                children: [
                  pw.Container(width: 14),
                  pw.Expanded(
                    flex: 5,
                    child: pw.Text(t.label,
                        style: const pw.TextStyle(fontSize: 10)),
                  ),
                  pw.Expanded(
                    flex: 4,
                    child: _bar(tFrac, color, height: 5),
                  ),
                  pw.SizedBox(width: 10),
                  pw.SizedBox(
                    width: 60,
                    child: pw.Text(formatHm(t.total),
                        textAlign: pw.TextAlign.right,
                        style: const pw.TextStyle(fontSize: 10)),
                  ),
                ],
              ),
            );
          }),
        ],
      ),
    );
  }

  /// A rounded progress bar filled [fraction] (0..1) in [color].
  pw.Widget _bar(double fraction, PdfColor color, {double height = 8}) {
    final f = fraction.clamp(0.0, 1.0);
    final filled = (f * 1000).round();
    return pw.ClipRRect(
      horizontalRadius: height / 2,
      verticalRadius: height / 2,
      child: pw.Row(
        children: [
          if (filled > 0)
            pw.Expanded(
                flex: filled,
                child: pw.Container(height: height, color: color)),
          if (filled < 1000)
            pw.Expanded(
                flex: 1000 - filled,
                child:
                    pw.Container(height: height, color: PdfColors.grey300)),
        ],
      ),
    );
  }

  /// Opens the system share sheet (Android) / save dialog (Windows).
  Future<void> share(pw.Document doc,
      {String filename = 'attendease_report.pdf'}) async {
    await Printing.sharePdf(bytes: await doc.save(), filename: filename);
  }

  /// Opens the print preview on both platforms.
  Future<void> printPreview(pw.Document doc) async {
    await Printing.layoutPdf(onLayout: (_) async => doc.save());
  }
}
